// Generated by Based — do not edit manually
// 2026-05-24T16:21:01.913Z

export interface Tables {
  dailyCounts: {
    id: string;
    count: number;
    clientUpdatedAt: number;
    createdAt: number;
    updatedAt: number;
  };
  progress: {
    id: string;
    kanaCompleted: number;
    onboardingDone: number;
    clientUpdatedAt: number;
    createdAt: number;
    updatedAt: number;
  };
  reviewStates: {
    id: string;
    fsrs: string;
    phase: string;
    clientUpdatedAt: number;
    createdAt: number;
    updatedAt: number;
  };
  settings: {
    id: string;
    newCardsPerDay: number;
    paletteId: string;
    dark: number;
    jaFont: string;
    clientUpdatedAt: number;
    createdAt: number;
    updatedAt: number;
  };
}

export type TableName = keyof Tables;
export type Row<T extends TableName> = Tables[T];
